#!/bin/bash

# Pimoroni Product Setup Dashboard
# Provides a familiar GUI for choosing which product installer to run

# original imgur script by Bart Nagel <bart@tremby.net>
# modified from version 4
# API Key provided by Alan@imgur.com

: <<'DISCLAIMER'

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

This script is licensed under the terms of the MIT license.
Unless otherwise noted, code reproduced herein
was written for this script.

- The Pimoroni Crew -

DISCLAIMER

productname="Pimstaller" # the name of the product to install
scriptname="pimstaller" # the name of this script
debugmode="no" # whether the script should use test Git user, branch and routines
forcesudo="no" # whether the script requires to be ran with root privileges
promptreboot="yes" # whether the script should always prompt user to reboot
customcmd="no" # whether to execute commands specified before exit
armv6="yes" # whether armv6 processors is supported or not
armv7="yes" # whether armv7 processors is supported or not
armv8="yes" # whether armv8 processors is supported or not
raspbianonly="yes" # whether the script is allowed to run on other OSes
squeezesupport="no" # whether Squeeze is supported or not
wheezysupport="yes" # whether Wheezy is supported or not
jessiesupport="yes" # whether Jessie is supported or not

confirm() {
    if [ "$FORCE" == '-y' ]; then
        true
    else
        read -r -p "$1 [y/N] " response < /dev/tty
        if [[ $response =~ ^(yes|y|Y)$ ]]; then
            true
        else
            false
        fi
    fi
}

success() {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning() {
    echo "$(tput setaf 1)$1$(tput sgr0)"
}

newline() {
    echo ""
}

sudocheck() {
    if [ $(id -u) -ne 0 ]; then
        echo -e "Install must be run as root. Try 'sudo ./$scriptname'\n"
        exit 1
    fi
}

sysclean() {
    sudo apt-get clean && sudo apt-get autoclean
    sudo apt-get -y autoremove &> /dev/null
}

sysupdate() {
    sudo apt-get update
}

sysupdgrade() {
    sudo apt-get update && sudo apt-get upgrade
    sudo apt-get clean && sudo apt-get autoclean
    sudo apt-get -y autoremove &> /dev/null
}

sysreboot() {
    warning "Some changes made to your system require"
    warning "your computer to reboot to take effect."
    newline
    if confirm "Would you like to reboot now?"; then
        sync
        sudo reboot
    fi
}

arch_check() {
    IS_ARMv6=false

    if uname -m | grep "armv6l" > /dev/null; then
        IS_ARMv6=true
    fi
}

os_check() {
    IS_RASPBIAN=false
    IS_MACOSX=false
    IS_X86_64=false
    IS_X86_32=false

    if [ -f /etc/os-release ] && cat /etc/os-release | grep "Raspbian" > /dev/null; then
        IS_RASPBIAN=true
    elif uname -s | grep "Darwin" > /dev/null; then
        IS_MACOSX=true
    elif uname -m | grep "x86_64" > /dev/null; then
        IS_X86_64=true
    else
        IS_X86_32=true
    fi
}

raspbian_check() {
    IS_SQUEEZE=false
    IS_WHEEZY=false
    IS_JESSIE=false

    if [ -f /etc/os-release ]; then
        if cat /etc/os-release | grep "jessie" > /dev/null; then
            IS_JESSIE=true
        elif cat /etc/os-release | grep "wheezy" > /dev/null; then
            IS_WHEEZY=true
        elif cat /etc/os-release | grep "squeeze" > /dev/null; then
            IS_SQUEEZE=true
        else
            echo "Unsupported distribution"
            exit 1
        fi
    fi
}

raspbian_old() {
    if $IS_SQUEEZE || $IS_WHEEZY ;then
        true
    else
        false
    fi
}

home_dir() {
    if ! $IS_MACOSX; then
        if [ $EUID -ne 0 ]; then
            USER_HOME=$(getent passwd $USER | cut -d: -f6)
        else
            if $SUDO_USER; then
                USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
            else
                warning "Running as root and no other sudo user available"
                exit 1
            fi
        fi
    else
        if [ $EUID -ne 0 ]; then
            USER_HOME=$(dscl . -read /Users/$USER NFSHomeDirectory | cut -d: -f2)
        else
            USER_HOME=$(dscl . -read /Users/$SUDO_USER NFSHomeDirectory | cut -d: -f2)
        fi
    fi
}

check_network() {
    sudo ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && return 0 || return 1
}

get_install() {
    check_network || (whip_msgbox "You don't appear to be connected to the internet, please check your connection and try again!" && exit 1)

    \curl -sS get.pimoroni.com/$1 | bash

    read -p "Press [Enter] key to continue..." < /dev/tty

    pim_menu
}

imgur_upload() {
    file="$1"
    apikey="b3625162d3418ac51a9ee805b1840452"

    response=$(curl -F "key=$apikey" -H "Expect: " -F "image=@$file" \
    http://imgur.com/api/upload.xml 2>/dev/null)
    # the "Expect: " header is to get around a problem when using this through 
    # the Squid proxy. Not sure if it's a Squid bug or what.
    if [ $? -ne 0 ]; then
        echo "Upload failed" >&2
    elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
        echo "Error message from imgur:" >&2
        echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
    fi

    url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
    deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
    echo $url
    return 0
}

take_snap() {
    if ! command -v scrot > /dev/null; then
        warning "scrot is not installed" 
        echo "try: sudo apt-get install scrot"
    else
        whip_msgbox "Please hit enter and then select the area you would like to screenshot by drawing a rectangle with your mouse.\n\nMake sure to move this window out of the way first!\n\nWarning!\nThis screenshot will be uploaded to imgur so you can share it with us, make sure it's not showing anything sensitive!"
        echo "Taking screenshot..."
        echo "Draw a rectangle around your subject."
        export PIMCWD=$(pwd)
        cd /tmp
        export IMGNAME=`scrot '%Y-%m-%d-pimoroni-help.png' -s -e 'echo $f'`
        export IMGURL=$(imgur_upload $IMGNAME)
        #rm $IMGNAME
        cd $PIMCWD
        whip_msgbox "Okay, your screenshot has been uploaded to:\n\n$IMGURL\n\nInclude this URL in your support query, and we'll be able to better identify your problem!\n\nYou can also find it in /tmp/$IMGNAME"
    fi
}

whip_confirm() {
    whiptail --yesno "$1" $WT_HEIGHT $(($WT_WIDTH-20))
}

whip_msgbox() {
    whiptail --msgbox "$1" $WT_HEIGHT $(($WT_WIDTH-20))
}

whip_size() {
    WT_HEIGHT=17
    WT_WIDTH=$(tput cols)
    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
        WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 178 ]; then
        WT_WIDTH=120
    fi
    WT_MENU_HEIGHT=$(($WT_HEIGHT-8))
}

pim_install() {
    if [ ! -f $DESKTOP_FILE ]; then
        if whip_confirm "Do you want to add Pimstaller to your desktop?"; then
            export TMPDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
            curl -sS get.pimoroni.com/pimoroni-dashboard.png >> $TMPDIR/pimstaller.png
            curl -sS get.pimoroni.com/pimstaller >> $TMPDIR/pimstaller
            sudo cp $TMPDIR/pimstaller.png $DESKTOP_ICON
            sudo cp $TMPDIR/pimstaller $DASHBOARD_SCRIPT
            sudo chmod +x $DASHBOARD_SCRIPT
            sudo gtk-update-icon-cache
            echo "\
[Desktop Entry]
Encoding=UTF-8
Name=Pimstaller
GenericName=Pimstaller
Comment=Manage software for Pimoroni products
TryExec=lxterminal
Exec=lxterminal --command $DASHBOARD_SCRIPT
Icon=$DESKTOP_ICON
Type=Application
Categories=Utility;\
" >> $TMPDIR/pimstaller.desktop

            sudo desktop-file-install $TMPDIR/pimstaller.desktop
            cp $DESKTOP_APP_FILE $DESKTOP_FILE
            rm -rf $TMPDIR

            rm -rf $TMPDIR
        fi
    fi
}

pim_uninstall() {
    sudo rm $DASHBOARD_SCRIPT
    sudo rm $DESKTOP_ICON
    sudo rm $DESKTOP_FILE
    sudo rm $DESKTOP_APP_FILE
    whip_msgbox "Pimstaller uninstalled!"
}

pim_update() {
    if check_network && [ -f $DESKTOP_FILE ]; then
        if [[ $1 == 'noupdate' ]]; then
            return
        fi
        echo "Updating..."
        export TMPDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
        curl -sS get.pimoroni.com/pimoroni-dashboard.png >> $TMPDIR/pimstaller.png
        curl -sS get.pimoroni.com/pimstaller >> $TMPDIR/pimstaller
        sudo cp $TMPDIR/pimstaller.png $DESKTOP_ICON
        sudo cp $TMPDIR/pimstaller $DASHBOARD_SCRIPT
        rm -rf $TMPDIR
        pimstaller noupdate
        exit 0
    fi
}

pim_menu() {
    FUNCTION=$(whiptail --title "Pimoroni Software Installer" --menu "Choose your add-on..." $WT_HEIGHT $(($WT_WIDTH-10)) $WT_MENU_HEIGHT \
    --cancel-button Quit \
    --ok-button Select \
    "01 Blinkt!" "Install software & examples" \
    "02 Display-o-Tron 3000/HAT" "Install software & examples" \
    "03 Drum HAT" "Install software & examples" \
    "04 Enviro pHAT" "Install software & examples" \
    "05 Explorer HAT/pHAT" "Install software & examples" \
    "06 ESP IoT pHAT" "Install software & examples" \
    "07 Micro Dot pHAT" "Install software & examples" \
    "08 pHAT DAC" "Install software & examples" \
    "09 Piano HAT" "Install software & examples" \
    "10 Pibrella" "Install software & examples" \
#    "11 PiGlow" "Install software & examples" \
#    "12 Scroll pHAT" "Install software & examples" \
#    "13 Skywriter HAT" "Install software & examples" \
#    "14 Unicorn HAT/pHAT" "Install software & examples" \
#    "99 Take Screenshot" "Useful to help solve a problem" \
    3>&1 1>&2 2>&3)

    RETURN=$?
    if [ $RETURN -eq 1 ]; then
        return 0
    elif [ $RETURN -eq 0 ]; then
        case "$FUNCTION" in
            01\ *) get_install blinkt ;;
            02\ *) get_install displayotron ;;
            03\ *) get_install drumhat ;;
            04\ *) get_install envirophat ;;
            05\ *) get_install explorerhat ;;
            06\ *) get_install iotphat ;;
            07\ *) get_install microdotphat ;;
            08\ *) get_install phatdac ;;
            09\ *) get_install pianohat ;;
            10\ *) get_install pibrella ;;
#            11\ *) get_install piglow ;;
#            12\ *) get_install scrollphat ;;
#            13\ *) get_install skywriter ;;
#            14\ *) get_install unicornhat ;;
#            99\ *) take_snap ;;
            *) whip_msgbox "Error: unrecognized option";;
        esac ||whip_msgbox "There was an error running option $FUNCTION"
    fi
}

about_msg() {
    whip_msgbox "\
This handy tool will help you get started with Pimoroni products. Simply pick the add-on board you want to install software for from the list, hit select and we'll walk you through the install process in a few easy steps.

Enjoy

- The Pimoroni Crew\
"
}

: <<'MAINSTART'

Perform all global variables declarations as well as function definition
above this section for clarity, thanks!

MAINSTART

arch_check
os_check
whip_size
home_dir

PIM_VERSION=1
WORKING_DIR="$USER_HOME/Pimoroni"
DESKTOP_FILE="$USER_HOME/Desktop/pimstaller.desktop"
DESKTOP_APP_FILE="/usr/share/applications/pimstaller.desktop"
DESKTOP_ICON="/usr/share/pixmaps/pimstaller.png"
DASHBOARD_SCRIPT="/usr/bin/pimstaller"

[ -d $WORKING_DIR ] || mkdir $WORKING_DIR
cd $WORKING_DIR

if $IS_RASPBIAN; then
    raspbian_check
    if [ $squeezesupport == "no" ] && $IS_SQUEEZE; then
        newline
        warning "--- Warning ---"
        newline
        echo "The $productname installer"
        echo "does not work on this version of Raspbian."
        echo "Check https://github.com/$gitusername/$gitreponame"
        echo "for additional information and support"
        newline
        exit 1
    fi
    if [ $wheezysupport == "no" ] && $IS_WHEEZY; then
        newline
        warning "--- Warning ---"
        newline
        echo "The $productname installer"
        echo "does not work on this version of Raspbian."
        echo "Check https://github.com/$gitusername/$gitreponame"
        echo "for additional information and support"
        newline
        exit 1
    fi
elif ! $IS_RASPBIAN && [ $raspbianonly == "yes" ]; then
    warning "Warning!"
    echo "Please only run this script on Raspbian on your Raspberry Pi"
    exit 1
else
    if [ $debugmode != "no" ]; then
        newline
        echo "IS_RASPBIAN is $IS_RASPBIAN"
        echo "IS_MACOSX is $IS_MACOSX"
        echo "IS_X86_64 is $IS_X86_64"
        echo "IS_X86_32 is $IS_X86_32"
    fi
fi

if [ $forcesudo == "yes" ]; then
    sudocheck
fi

if [[ $1 == 'uninstall' ]]; then
    pim_uninstall
else
    pim_update $1
    about_msg
    pim_menu
    pim_install
fi
